image: maven:3-jdk-8 

build:
    script: "mvn install -B --fail-at-end -B  -Dmatsim.preferLocalDtds=true" 
#  -Dmaven.test.redirectTestOutputToFile 

# see http://stackoverflow.com/questions/33430487/how-to-use-gitlab-ci-to-build-a-java-maven-project 
#
