image: maven:3-jdk-8

stages:
    - test
    - build
    - deploy

#run tests for every commit
test:
    stage: test
    script: "mvn test --batch-mode"

#run the build with artifacts only for commits to develop and master after tests were run
build:
    stage: build
    only:
      - master
      - develop
    script: "mvn install -DskipTests --batch-mode"
    artifacts:
      when: on_success
      paths:
        - auth/target/*.jar
        - files/target/*.jar