image: maven:3-jdk-8

stages:
    - test
    - build
    - deploy

#run tests for every commit
test:
    stage: test
    script: "mvn test --batch-mode"

#run the build with artifacts only for commits to develop and master after tests were run
build:
    stage: build
    only:
      - master
      - develop
    script: "mvn install -DskipTests --batch-mode"
    artifacts:
      when: on_success
      paths:
        - auth/target/auth-*-jar-with-dependencies.jar
        - files/target/files-*-jar-with-dependencies.jar
deploy:
    stage: deploy
    only:
        - master
        - develop
    dependencies: 
        - build  
    script:
        - which ssh-agent
        - eval $(ssh-agent -s)
        - ssh-add <(echo "$SSH_PRIVATE_KEY")
        - '[[ -f /.dockerenv ]] && mkdir -p ~/.ssh && echo "$KNOWN_HOST" > ~/.ssh/known_hosts'
        - ssh webvis@cnode00.vsp.tu-berlin.de 'sudo service webvis-files stop'
        - ssh webvis@cnode00.vsp.tu-berlin.de 'sudo service webvis-auth stop'
        - ls -lhaA auth/target/
        - ls -lhaA 
        - scp auth/target/auth-*-jar-with-dependencies.jar webvis@cnode00.vsp.tu-berlin.de:/home/webvis/matsim-webvis-auth/auth-server.jar
        - scp files/target/files-*-jar-with-dependencies.jar webvis@cnode00.vsp.tu-berlin.de:/home/webvis/matsim-webvis-files/file-server.jar
        - ssh webvis@cnode00.vsp.tu-berlin.de 'sudo service webvis-auth start'
        - ssh webvis@cnode00.vsp.tu-berlin.de 'sudo service webvis-files start'