image: maven:3-jdk-8

stages:
    - build
    - deploy

package-auth:
    stage: build
    script: "mvn package assembly:single --file auth/pom.xml --batch-mode"
    artifacts:
        name: "auth-server"
        paths:
            - target/*.jar

package-files:
    stage: build
    script: "mvn package assembly:single --file files/pom.xml --batch-mode"
    artifacts:
        name: "file-server"
        paths:
            - target/*.jar