image: maven:3-jdk-8

stages:
    - build
    - deploy

build:
    stage: build
    script: "mvn install --batch-mode"
    artifacts:
      paths:
        - auth/target/*.jar
        - files/target/*.jar