language: java

before_deploy:
  - ./aws-deploy/deploy.sh auth 1.0-SNAPSHOT

deploy:
  on:
    branch: develop
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id: $BEANSTALK_KEY_ID
  secret_access_key:
    secure: $BEANSTALK_KEY
  region: eu-central-1
  env: authentication
  app: matsim-viz-server
  zip_file: ./auth/target/auth-1.0-SNAPSHOT.jar
  bucket_name: elasticbeanstalk-eu-central-1-760858299633
  
