language: java
sudo: required
dist: trusty
addons:
  ssh_known_hosts:
    - cnode00.vsp.tu-berlin.de

script: mvn clean install

deploy:
  - on:
      branch: develop
    provider: script
    script: bash ./vsp-deploy/deploy.sh -dev
    skip_cleanup: true
  - on:
      branch: master
    provider: script
    script: bash ./vsp-deploy/deploy.sh
    skip_cleanup: true